# Generated by Django 6.0.2 on 2026-03-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('supplier', models.CharField(max_length=100)),
            ],
        ),
    ]
