# Generated by Django 6.0.2 on 2026-03-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0002_brand_remove_product_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
